"""Passo 3: tabelas conversa, mensagem, escalada

Revision ID: 058b58ebedb9
Revises: 
Create Date: 2026-06-16 17:30:41.453161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '058b58ebedb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_whatsapp', sa.String(length=20), nullable=False),
    sa.Column('paciente_hamilton_id', sa.Integer(), nullable=True),
    sa.Column('modo', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('dados_coletados', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversa_modo'), ['modo'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversa_numero_whatsapp'), ['numero_whatsapp'], unique=True)

    op.create_table('escalada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversa_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=50), nullable=False),
    sa.Column('contexto', sa.Text(), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolvida_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escalada', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escalada_conversa_id'), ['conversa_id'], unique=False)

    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversa_id', sa.Integer(), nullable=False),
    sa.Column('direcao', sa.String(length=10), nullable=False),
    sa.Column('origem', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('whatsapp_message_id', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mensagem', schema=None) as batch_op:
        batch_op.create_index('idx_mensagem_conversa', ['conversa_id', 'criada_em'], unique=False)
        batch_op.create_index('idx_mensagem_whatsapp_id', ['whatsapp_message_id'], unique=True, postgresql_where=sa.text('whatsapp_message_id IS NOT NULL'), sqlite_where=sa.text('whatsapp_message_id IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagem', schema=None) as batch_op:
        batch_op.drop_index('idx_mensagem_whatsapp_id', postgresql_where=sa.text('whatsapp_message_id IS NOT NULL'), sqlite_where=sa.text('whatsapp_message_id IS NOT NULL'))
        batch_op.drop_index('idx_mensagem_conversa')

    op.drop_table('mensagem')
    with op.batch_alter_table('escalada', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escalada_conversa_id'))

    op.drop_table('escalada')
    with op.batch_alter_table('conversa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversa_numero_whatsapp'))
        batch_op.drop_index(batch_op.f('ix_conversa_modo'))

    op.drop_table('conversa')
    # ### end Alembic commands ###
