"""desconto oferecido pela Sofia na conversa

Revision ID: fd757db2682f
Revises: d6e7f8a9b0c1
Create Date: 2026-08-08 01:33:18.548976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd757db2682f'
down_revision: Union[str, None] = 'd6e7f8a9b0c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desconto_oferecido_em', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('desconto_valor', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('desconto_motivo', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversa', schema=None) as batch_op:
        batch_op.drop_column('desconto_motivo')
        batch_op.drop_column('desconto_valor')
        batch_op.drop_column('desconto_oferecido_em')

    # ### end Alembic commands ###
